In [1]:
import pandas as pd

import numpy as np

import seaborn as sns

from sklearn import linear_model 



In [2]:
df=pd.read_csv("insurance1.csv")

In [4]:
df

Unnamed: 0  age  height  weight  premium
0           0   25  162.56      70    18000
1           1   30  172.72      95    38000
2           2   35  167.64      78    38000
3           3   40     NaN     110    60000
4           4   45  157.48      85    70000

In [7]:
mean_height=df.height.mean()

In [13]:
df.height=df.height.fillna(mean_height)

In [14]:
df

Unnamed: 0  age  height  weight  premium
0           0   25  162.56      70    18000
1           1   30  172.72      95    38000
2           2   35  167.64      78    38000
3           3   40  165.10     110    60000
4           4   45  157.48      85    70000

In [15]:
reg=linear_model.LinearRegression()

In [16]:
reg.fit(df[["age", "height", "weight"]], df["premium"])

LinearRegression()

In [17]:
reg.intercept_

-16827.01315482489

In [18]:
reg.coef_

array([2150.26052416, -248.45851574,  312.65291961])

In [20]:
reg.predict([[27,165.78,60]])

C:\Users\Milan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([18799.74343492])

In [21]:
reg.predict([[78,98,20]])

C:\Users\Milan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([132797.43157946])